# Generated by Django 4.2 on 2025-12-18 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classname',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=50, unique=True)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Classname',
                'verbose_name_plural': 'Classnames',
                'db_table': 'class_info',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_instraction', models.CharField(max_length=5000)),
                ('notice_photo', models.ImageField(blank=True, null=True, upload_to='notice_photos/')),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NoticeInstruction',
                'db_table': 'Notice',
                'ordering': ['notice_id'],
            },
        ),
        migrations.CreateModel(
            name='rescuedFeesRecord',
            fields=[
                ('fees_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=1000)),
                ('father_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('paid_at', models.DateField(auto_now_add=True)),
                ('remark', models.CharField(default='Paid', max_length=1000)),
                ('mode', models.CharField(default='Cash', max_length=1000)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paying_month', models.BooleanField(default=False)),
                ('how_many_month', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'RoutineEntry',
                'db_table': 'Routine_Entry',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Website_Details_For_Easy_Access',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_logo', models.ImageField(upload_to='website_details_metadata')),
                ('website_name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'info',
                'db_table': 'Website_Details',
            },
        ),
        migrations.CreateModel(
            name='Study_Materials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=1000)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='study_materials')),
                ('visibility', models.BooleanField(default=True)),
                ('enable_date', models.DateField(blank=True, null=True)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='TeacherPanel.classname')),
            ],
            options={
                'verbose_name': 'StudyMaterial',
                'db_table': 'Study_Materials',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(editable=False, max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('studentname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('admission_date', models.DateField(default=datetime.date(2025, 5, 5))),
                ('year_outstanding', models.DecimalField(decimal_places=2, default=250.0, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='TeacherPanel.batch')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='TeacherPanel.classname')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student_info',
                'ordering': ['studentname'],
            },
        ),
        migrations.CreateModel(
            name='Online_Class_Link',
            fields=[
                ('class_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_date', models.DateField()),
                ('time', models.TimeField()),
                ('subject', models.CharField(max_length=100)),
                ('class_link', models.URLField()),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_class_links', to='TeacherPanel.batch')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_class_links', to='TeacherPanel.classname')),
            ],
            options={
                'verbose_name': 'OnlineClassLink',
                'db_table': 'Online_Class_Link',
                'ordering': ['classname', 'batch', 'class_date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='FeesRecord',
            fields=[
                ('fees_id', models.AutoField(primary_key=True, serialize=False)),
                ('paid_at', models.DateField(auto_now_add=True)),
                ('remark', models.CharField(default='Paid', max_length=1000)),
                ('mode', models.CharField(default='Cash', max_length=1000)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paying_month', models.BooleanField(default=False)),
                ('how_many_month', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='TeacherPanel.student')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='TeacherPanel.classname'),
        ),
    ]
