# Generated by Django 4.2 on 2025-10-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classname',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=50, unique=True)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Classname',
                'verbose_name_plural': 'Classnames',
                'db_table': 'class_info',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='media/student_photos/')),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='TeacherPanel.batch')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='TeacherPanel.classname')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student_info',
                'ordering': ['studentname'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='TeacherPanel.classname'),
        ),
    ]
