# Generated by Django 4.2 on 2025-10-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_instraction', models.CharField(max_length=5000)),
                ('notice_photo', models.ImageField(upload_to='media/notice_photos/')),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NoticeInstruction',
                'db_table': 'Notice',
                'ordering': ['notice_id'],
            },
        ),
    ]
