# Generated by Django 4.2 on 2025-12-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='galleryItem/')),
            ],
        ),
    ]
