# Generated by Django 4.2 on 2025-12-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='raw_password',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
