# Generated by Django 4.2 on 2025-10-26 18:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0002_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_Details_For_Easy_Access',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_logo', models.ImageField(upload_to='website_details_metadata')),
                ('website_name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'info',
                'db_table': 'Website_Details',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='year_outstanding',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_photo',
            field=models.ImageField(blank=True, null=True, upload_to='notice_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=datetime.date(2025, 5, 5)),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='student_photos/'),
        ),
        migrations.CreateModel(
            name='FeesRecord',
            fields=[
                ('fees_id', models.AutoField(primary_key=True, serialize=False)),
                ('paid_at', models.DateField(auto_now_add=True)),
                ('remark', models.CharField(default='Paid', max_length=1000)),
                ('mode', models.CharField(default='Cash', max_length=1000)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='TeacherPanel.student')),
            ],
        ),
    ]
