# Generated by Django 4.2 on 2025-12-31 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0003_student_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
        ),
    ]
