# Generated by Django 4.2 on 2025-10-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0003_website_details_for_easy_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesrecord',
            name='paying_month',
            field=models.BooleanField(default=False),
        ),
    ]
