# Generated by Django 4.2 on 2025-12-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0004_alter_student_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(),
        ),
    ]
