# Generated by Django 4.2 on 2025-10-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0004_feesrecord_paying_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesrecord',
            name='how_many_month',
            field=models.IntegerField(default=0),
        ),
    ]
