# Generated by Django 4.2 on 2025-11-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0005_feesrecord_how_many_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=20)),
                ('day_name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routine_entries', to='TeacherPanel.batch')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_entries', to='TeacherPanel.classname')),
            ],
            options={
                'verbose_name': 'RoutineEntry',
                'db_table': 'Routine_Entry',
                'ordering': ['classname', 'day_of_week', 'start_time'],
            },
        ),
    ]
