# Generated by Django 4.2 on 2025-11-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0006_routineentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineentry',
            name='end_time',
            field=models.TimeField(default=models.TimeField()),
        ),
    ]
