# Generated by Django 4.2 on 2025-11-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0007_alter_routineentry_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_Class_Link',
            fields=[
                ('class_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_date', models.DateField()),
                ('time', models.TimeField()),
                ('subject', models.CharField(max_length=100)),
                ('class_link', models.URLField()),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_class_links', to='TeacherPanel.batch')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_class_links', to='TeacherPanel.classname')),
            ],
            options={
                'verbose_name': 'OnlineClassLink',
                'db_table': 'Online_Class_Link',
                'ordering': ['classname', 'batch', 'class_date', 'time'],
            },
        ),
    ]
