# Generated by Django 4.2 on 2025-11-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0008_online_class_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routineentry',
            options={'ordering': ['start_time'], 'verbose_name': 'RoutineEntry'},
        ),
        migrations.RemoveField(
            model_name='routineentry',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='routineentry',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='routineentry',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='routineentry',
            name='end_time',
        ),
    ]
