# Generated by Django 4.2 on 2025-12-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0009_alter_routineentry_options_remove_routineentry_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rescuedFeesRecord',
            fields=[
                ('fees_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=1000)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='rescued_student_photos/')),
                ('paid_at', models.DateField(auto_now_add=True)),
                ('remark', models.CharField(default='Paid', max_length=1000)),
                ('mode', models.CharField(default='Cash', max_length=1000)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paying_month', models.BooleanField(default=False)),
                ('how_many_month', models.IntegerField(default=0)),
            ],
        ),
    ]
