# Generated by Django 4.2 on 2025-12-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0010_rescuedfeesrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescuedfeesrecord',
            name='student_photo',
        ),
        migrations.AddField(
            model_name='rescuedfeesrecord',
            name='father_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rescuedfeesrecord',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
