# Generated by Django 4.2 on 2025-12-13 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPanel', '0011_remove_rescuedfeesrecord_student_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Materials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=1000)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='study_materials')),
                ('visibility', models.BooleanField(default=True)),
                ('enable_date', models.DateField(blank=True, null=True)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='TeacherPanel.classname')),
            ],
            options={
                'verbose_name': 'StudyMaterial',
                'db_table': 'Study_Materials',
                'ordering': ['-upload_date'],
            },
        ),
    ]
